---
- name: "Grading Example Playbook"
  hosts: all
  become: yes

  tasks:
  - name: "Check if file exists"
    stat:
      path: "/home/{{ login }}/.bashrc"
    register: r

  - name: "Available variable"
    debug:
      msg: "login = {{ login }} || domain = {{ domain }} || user = {{ user }}"

  - name: "Result"
    debug:
      msg: "you have earned 100 point out of 0"
    when: r.stat.exists
